extends Node

@warning_ignore("unused_signal")
signal OnTabBtnpressed(btn_tab_node:ButtonTabClass)
@warning_ignore("unused_signal")
signal StopScreenClick(to_stop:bool)
@warning_ignore("unused_signal")
signal SetTopSubTitle(sub_title:String)
@warning_ignore("unused_signal")
signal OnProgressTabPressed(btn_tab_node:ProgressTabClass)
@warning_ignore("unused_signal")
signal OnWorldSkillClassSelected(SkillNode:WorldSkillClass)
@warning_ignore("unused_signal")
signal ResetSkillCamera()
@warning_ignore("unused_signal")
signal CenterCameraCurSelectedSkill()
@warning_ignore("unused_signal")
signal OpenCloseSettingMenu(to_open)
@warning_ignore("unused_signal")
signal ShowPopup(popup_name:String)
@warning_ignore("unused_signal")
signal CloseCurPopup()
@warning_ignore("unused_signal")
signal DataSaved()
@warning_ignore("unused_signal")
signal StartDragMergeItem(merge_item:MergeItemClass)
@warning_ignore("unused_signal")
signal StartDragBotItem(bot_item:DigBotClass)
@warning_ignore("unused_signal")
signal ShowCurrencyAnimation(from_glob_pos:Vector2,currency_type:String,value:int)
@warning_ignore("unused_signal")
signal ShowChestAnimation(from_glob_pos:Vector2,chest_type:String)
@warning_ignore("unused_signal")
signal CurrencyAdded(currency_type:String,currency_amount:int)
@warning_ignore("unused_signal")
signal OpenTabFromStr(tab_name:String)
@warning_ignore("unused_signal")
signal AllQuestsInited()
@warning_ignore("unused_signal")
signal SkillsFinishedCreating()
@warning_ignore("unused_signal")
signal OnSkillLevelUpdated(skill_id:String)
@warning_ignore("unused_signal")
signal SyncActivatedBooster(booster_id:String)
@warning_ignore("unused_signal")
signal OnRelicUpgradeSelected(relic_item:RelicUpgradeItemClass)
@warning_ignore("unused_signal")
signal OnRelicSynced()
@warning_ignore("unused_signal")
signal OnShowAllSkillsToggled(is_toggled)
